# Generated by Django 4.2.4 on 2023-10-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fio',
            field=models.CharField(default='', max_length=255, verbose_name='FIO'),
        ),
    ]
