# Generated by Django 4.2.4 on 2023-12-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes_load', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes_load',
            name='serialNum',
            field=models.TextField(),
        ),
    ]
