# Generated by Django 4.2.4 on 2023-12-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes_load', '0003_rename_serialnum_codes_load_passfile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codes_load',
            options={'verbose_name': 'Subscriptions test Files', 'verbose_name_plural': 'Subscriptions test Files'},
        ),
    ]
