# Generated by Django 4.2.4 on 2023-12-06 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('serialNum', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('loadDate', models.DateField(auto_now_add=True)),
                ('ignor', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('soldDate', models.DateField(auto_now=True)),
                ('orderId', models.IntegerField(blank=True)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
        ),
    ]
