# Generated by Django 4.2.4 on 2023-12-06 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_phone'),
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='orders.order'),
            preserve_default=False,
        ),
    ]
