# Generated by Django 4.2.4 on 2023-12-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_codes_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codes',
            name='orderId',
        ),
    ]
