# Generated by Django 4.2.4 on 2023-12-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0004_alter_codes_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codes',
            name='name',
        ),
    ]
