# Generated by Django 4.2.4 on 2023-12-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0005_remove_codes_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codes',
            options={'verbose_name': 'Subscriptions List', 'verbose_name_plural': 'Subscriptions List'},
        ),
    ]
