# Generated by Django 4.2.4 on 2023-12-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code_send',
            field=models.BooleanField(default=False),
        ),
    ]
